### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by Berkanktk** [amatzen/SE02-SE-G02-SPRO#204]
Søgefunktionen virker ikke ordentligt

**Comment by danielbahrami** [comment]
Kan du uddybe hvad der ikke virker ved den? Det virker umiddelbart fint for mig.

**Comment by Berkanktk** [comment]
> Kan du uddybe hvad der ikke virker ved den? Det virker umiddelbart fint for mig.

Oh what? Der intet jeg søger der kommer frem rigtigt

**Comment by Berkanktk** [comment]
![image](https://user-images.githubusercontent.com/68930825/119173487-9d656d80-ba67-11eb-8261-1302454f3de3.png)
![image](https://user-images.githubusercontent.com/68930825/119173509-a5251200-ba67-11eb-8cc6-88b83ae07780.png)

**Comment by Berkanktk** [comment]
Har prøvet med flere, og det fucker også op ved dem. Forstår ikke hvordan det bare virker for dig og ikke mig, seems weird

**Comment by danielbahrami** [comment]
Husk den er case sensitive

**Comment by Berkanktk** [comment]
Ah i see, glemte that
