### ISSUE TITLE
Wrong FXML file

### ISSUE THREAD

**Issue by Berkanktk** [amatzen/SE02-SE-G02-SPRO#205]
Når man går ind under Personer -> Handlinger -> rediger, kommer "Tilføj person" fxml filen op. Det er den forkerte fil, da det er den samme fil når man går under Person -> +

- Skal der evt. laves en ny med "Rediger Person" ?

**Comment by danielbahrami** [comment]
Tror bare den anvender samme modal fordi det er mere bekvemt.
Tænker man eventuelt kan sætte et fx:id på "Tilføj person" labelet, så hvis modalet åbnes gennem "Rediger" knappen så ændrer det teksten til "Rediger person".

**Comment by Berkanktk** [comment]
> Tror bare den anvender samme modal fordi det er mere bekvemt.
> Tænker man eventuelt kan sætte et fx:id på "Tilføj person" labelet, så hvis modalet åbnes gennem "Rediger" knappen så ændrer det teksten til "Rediger person".

Yea jeg tænkte præcis det samme. Vidste bare ikke om det ville fucke noget up ad vi bruger den samme fxml fil

**Comment by danielbahrami** [comment]
Tror ikke det skaber nogle problemer i selve programmet. Det er bare et visuelt problem.

**Comment by danielbahrami** [comment]
Kort opsummeret:
Der står "Tilføj virksomhed" og ikke "Rediger virksomhed".
Der står "Tilføj person" og ikke "Rediger person".
