### ISSUE TITLE
Exceptions when clicking "Personer"

### ISSUE THREAD

**Issue by Berkanktk** [amatzen/SE02-SE-G02-SPRO#206]
Exception in thread "Thread-12" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-12

**Comment by danielbahrami** [comment]
Hvor er "Person" henne som du refererer til?

**Comment by Berkanktk** [comment]
> Hvor er "Person" henne som du refererer til?
I programmet når man kører det. Jeg mente "Personer"* 
![image](https://user-images.githubusercontent.com/68930825/119174964-87f14300-ba69-11eb-80b5-e0106dd72aaf.png)

**Comment by danielbahrami** [comment]
Okay jeg får også en IllegalStateException. Det finder vi ud af.

**Comment by amatzen** [comment]
`IllegalStateException` skal blot ignoreres. @esbendamkjaer og jeg blev enige om det i hvert fald.
