### ISSUE TITLE
Farve for personers navn og rolle

### ISSUE THREAD

**Issue by jasannn** [amatzen/SE02-SE-G02-SPRO#211]
Når der trykkes "Se kreditering" under sektionen "Programmer" så viser modalen med personer. Personers navn og rolle skal stå med sort skrift istedet for hvid. Det er weird fordi inde i FXML filen så anvendes der en sort farve

**Comment by danielbahrami** [comment]
Jeg prøvede faktisk selv at fikse det, men ja det er mærkeligt fordi inde i FXML filen er det netop angivet til at være sort.

**Comment by jasannn** [comment]
tror du jeg er fejlfri??!!!
